# Generated by Django 3.2.14 on 2022-12-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0004_remove_posteo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='post',
            new_name='posteoc',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='usuario',
        ),
    ]
