# Generated by Django 3.2.14 on 2022-12-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0006_alter_posteo_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='posteoc',
            new_name='posteo',
        ),
    ]
