# Generated by Django 3.2.14 on 2022-12-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0007_rename_posteoc_comentarios_posteo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Proyecto',
        ),
    ]
